version: v1.0
name: Deploy digital ocean
blocks:
  - name: Deploy
    task:
      secrets:
        - name: do-access-token
        - name: nhlbet-site
        - name: dockerhub
      prologue:
        commands:
          - doctl auth init --access-token $DO_ACCESS_TOKEN
          - doctl registry login
          - doctl kubernetes cluster kubeconfig save 1a0ac277-a3d7-40cc-81f7-0c9a6eb80387
          - checkout
      jobs:
        - name: Deployment
          commands:
            - checkout
            - source ./ci_cd/digitalocean/env-prod
            - docker build -t nhlbet-site .
            - docker tag nhlbet-site registry.digitalocean.com/mysportsbet/nhlbet-site:$SEMAPHORE_WORKFLOW_ID
            - docker push registry.digitalocean.com/mysportsbet/nhlbet-site:$SEMAPHORE_WORKFLOW_ID
            - source ./ci_cd/digitalocean/deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
